Add middleware function
DawMas/25.5-middleware pull request #1
Opened 2019-08-19 19:24 UTC by DawMas

Dodanie middleware

2019-08-28 03:45 UTC, lukaszewczak requested changes

2019-08-28 03:45 UTC, lukaszewczak commented on server.js
> +//app.use(express.static('assets'));
Nie zostawiamy za komentowanego kodu

2019-08-28 03:45 UTC, lukaszewczak commented on test.json
> +testujemy
Czemu ma służyć ten plik?

2019-08-29 16:57 UTC, DawMas commented on test.json
> +testujemy
został przez nieuwagę z poprzedniego zadania.. poprawione

2019-09-01 18:45 UTC, lukaszewczak approved these changes

2019-09-10 19:12 UTC, merged